#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"
require "pathname"

repo_root = Pathname.new(__dir__).join("../..").cleanpath
token_files = %w[
  design-tokens/mobile.primitives.tokens.json
  design-tokens/mobile.semantic.tokens.json
  design-tokens/mobile.component.tokens.json
]
output_path = repo_root.join("ios/SideStage/Sources/Generated/SideStageTokens.swift")

def flatten_tokens(node, prefix = [], output = {})
  if node.is_a?(Hash) && node.key?("$value")
    output[prefix.join(".")] = node.fetch("$value")
    return output
  end

  return output unless node.is_a?(Hash)

  node.each do |key, value|
    next if key.start_with?("$") || key == "_meta"

    flatten_tokens(value, prefix + [key], output)
  end
  output
end

def resolve_token(name, tokens, resolving = [])
  raise "Unknown token reference: #{name}" unless tokens.key?(name)
  raise "Circular token reference: #{(resolving + [name]).join(" -> ")}" if resolving.include?(name)

  value = tokens.fetch(name)
  match = value.is_a?(String) && value.match(/\A\{([^}]+)\}\z/)
  match ? resolve_token(match[1], tokens, resolving + [name]) : value
end

def swift_name(value)
  parts = value.split("-")
  parts.first + parts.drop(1).map(&:capitalize).join
end

tokens = token_files.each_with_object({}) do |relative_path, output|
  payload = JSON.parse(repo_root.join(relative_path).read)
  flatten_tokens(payload).each { |name, value| output[name] = value }
end

semantic_colors = %w[
  background surface surface-raised stage border text text-muted text-faint
  accent accent-strong violet warning success danger
]
component_colors = %w[
  primary-button-background primary-button-text live-indicator auction-leader bid-warning
]

color_lines = lambda do |group, names|
  names.map do |name|
    value = resolve_token("color.#{name}", tokens)
    raise "Expected a hex color for color.#{name}, got #{value.inspect}" unless value.match?(/\A#[0-9A-Fa-f]{6}(?:[0-9A-Fa-f]{2})?\z/)

    "        static let #{swift_name(name)} = SwiftUI.Color(hex: \"#{value.upcase}\")"
  end.join("\n")
end

minimum_touch_target = resolve_token("size.minimum-touch-target", tokens)
minimum_touch_points = Float(minimum_touch_target.delete_suffix("px"))

generated = <<~SWIFT
  // SPDX-License-Identifier: MIT
  // Generated by tools/build-scripts/generate-swift-design-tokens.rb. Do not edit.

  import SwiftUI

  enum SideStageTokens {
      enum Semantic {
  #{color_lines.call("Semantic", semantic_colors)}
      }

      enum Component {
  #{color_lines.call("Component", component_colors)}
          static let minimumTouchTarget: CGFloat = #{format("%g", minimum_touch_points)}
      }
  }

  private extension SwiftUI.Color {
      init(hex: String) {
          let value = UInt64(hex.dropFirst(), radix: 16) ?? 0
          let hasAlpha = hex.count == 9
          let red = Double((value >> (hasAlpha ? 24 : 16)) & 0xFF) / 255
          let green = Double((value >> (hasAlpha ? 16 : 8)) & 0xFF) / 255
          let blue = Double((value >> (hasAlpha ? 8 : 0)) & 0xFF) / 255
          let alpha = hasAlpha ? Double(value & 0xFF) / 255 : 1
          self.init(.sRGB, red: red, green: green, blue: blue, opacity: alpha)
      }
  }
SWIFT

if ARGV.include?("--check")
  abort("ERROR: #{output_path.relative_path_from(repo_root)} is stale; regenerate it") unless output_path.exist? && output_path.read == generated

  puts "✓ Swift design tokens are current"
else
  output_path.dirname.mkpath
  output_path.write(generated)
  puts "✓ Generated #{output_path.relative_path_from(repo_root)}"
end
